In [2]:
import pandas as pd
import numpy as np

In [4]:
da=pd.read_csv(r'C:\Users\CAC\Desktop\HENRY\DATA SCIENSE\1 CURSO DT08-GRUPO 03\M1\Clase 04 - PANDAS\fifa-statistics.csv',decimal=',' , )
dacopi=da.copy()

In [6]:
dacopi.head(2)

,Date,Team,Opponent,Goal Scored,Ball Possession %,Attempts,On-Target,Off-Target,Blocked,Corners,...,Yellow Card,Yellow & Red,Red,Man of the Match,1st Goal,Round,PSO,Goals in PSO,Own goals,Own goal Time
0,14-06-2018,Russia,Saudi Arabia,5,40,13,7,3,3,6,...,0,0,0,Yes,12.0,Group Stage,No,0,NaN,NaN
1,14-06-2018,Saudi Arabia,Russia,0,60,6,0,3,3,2,...,0,0,0,No,NaN,Group Stage,No,0,NaN,NaN

In [4]:
daa=da.head(2)
daa

,Entity,Code,Year,Coal_Consumption_EJ,Gas_Consumption_EJ,Geo_Biomass_Other_TWh,Hydro_Generation_TWh,Nuclear_Generation_TWh,Solar_Generation_TWh,Wind_Generation_TWh,Oil_Consumption_EJ
0,Africa,NaN,1965,1.164586098,0.034357515,0,13.90563517,0,0,0,1.173241355
1,Africa,NaN,1966,1.163239896,0.038411698,0,15.51000414,0,0,0,1.284153639

In [9]:
daf=dacopi[dacopi.Team == 'Russia']

In [5]:
daa.all()

Entity                    True
Code                      True
Year                      True
Coal_Consumption_EJ       True
Gas_Consumption_EJ        True
Geo_Biomass_Other_TWh     True
Hydro_Generation_TWh      True
Nuclear_Generation_TWh    True
Solar_Generation_TWh      True
Wind_Generation_TWh       True
Oil_Consumption_EJ        True
dtype: bool

In [1]:
#Instalar PANDAS
# -m pip install pandas ---> Desdes simbolo del sistema
#----------------------------------------------------------------------------------------
#CLASE  1

# La estrutura fundamental de Pandas es:
# SERIES  --> Solo posee un tipo de dato y es Similar a una array
# DATAFRAME --> Este puede ser creado uniendo varias series
#
# CREAR SERIES
#    ejemplo:
#    materias=pd.series(["Matematicas"," Histiria"," ingles"],dtype="string")
#
# BUSCAR DATOS Y/O CONSULTAS
#
#    1). materias=[ 2 ] R// Ingles
#    2). materias=[ : 2] R// "Matematicas"," Histiria"
#    3). materias.dtype --> Tipo de datos de la serie
#    4). materias.size --> cuantos elementos tiene
#    5). materias.index --> Donde Inicia y fnaliza
# METER DICCIONARIO DENTRO UNA SERIE
#    6). edades=pd.series(dict(JUAN=25,ROMINA=23,ROBERTO=43)) R// --> edades=[ JUAN ] R// 25
# CONTAR EN LAS SERIES
#    7). NUEMROS=PD.SERIES([2,4,7,9,NONE])
#        PRINT(NUMEROS.SIZE) ------> R// 5
#MINUTO  PRINT(LEN(NUMEROS.SIZE))--> R// 5
# 27     PRINT(NUMEROS.COUNT()) ---> R// 4 --> CUANTO SACANDO LOS NULOS
#        PRINT(NUMEROS.SUM()) ---> 22 SUMA TODOS LOS VALORES DE LA SERIE O CONCATENA
#----------------------------------------------------------------------------------------
#buscar en pandas PANDAS.DATAFRAME.--> EJEMPLO FILTER
#EXTRACION Y EXPORTACION
# EXTRACION ARCHIVOS CSV:
#da=pd.read_csv(r'datasets\Fuentes_Consumo_Energia.csv',decimal=',' , ) (ruta relativa)--> r-carpeta-archivo.csv
       #'thousand='.' , decimal=',' , index_col='columna' , 
#da=pd.read_csv(r'datasets\Fuentes_Consumo_Energia.csv',index_col='columna') permite escoger que columna 
#                       va a ser la columna identificadora OJO el indice es diferente.
#da=pd.read_csv("DataPlataformas.csv",sep=";",usecols=[0,1,8])#-->permite escoger que columna deseo extraer
# EXTRACION ARCHIVOS EXCEL:
# EXTRACION ARCHIVOS JAISON:
#--------------------------------------------------------------------------
# EXPORTACION A EXCEL
 # import pandas as pd
 # Df=pd.read_excel(io="Ruta .xlsx",sheet_name="hoja1",                             
 #                                   header=0,
 #                                   names=None,
 #                                   index_col=None,
 #                                   usecols="Nombre columna A:hasta L", 
 #                                   usecols="La columna A, y la L",
 #                                   engine="openpyxl")

# EXPORTACION A CSV

#---------------------------------------------------------------------------
#configuracion e informacion
#da.info()
#!python --version # Nos muestra la version de python
#pd.__version__  # Nos muestra la version de panda atra vez de su instacia 
#-------------------------------------------------------------------------
#VISUALIZACION

#da.describe() #Permite ver un resumen estadistico del dataframe
#da.columns() #Permite ver los nombresde las columnas
#da.sample(cant) #permite traer una o varias muestra al asar  
#da.head() # muestra las primeras 5 filas 
#da.head(cantida defilas que desee) # muestra las filas que deseemos
#da.tail()# muestra las ultimas 5 filas 
#da.tail(cantida defilas que desee)  # muestra las filas que deseemos
#da[['column 1','column 2','column 3]] #permite visualizar todas las columnas que queramos
#da[['column x']] #permite visualizar una columna
#da['column 1'].unique() # permite visualizar una columna con valores unicos
#da.duplicated() #busca el duplicado de toda la fila muestra valores booleanos
#da.duplicated('nombre de la columna') 
#da[["nombre columna 1",""nombre columna 2"]].style.hide(axis="index")#-->Oculta los indices de cada fila
#da[["nombre columna 1",""nombre columna 2"]].style.format(precision=0)#-->Modifica la cantidad de decimal de las columnas
#da[["col1","col2"]].style.hide(axis="index").format(precision=0)#-->Oculta indices de fila y Modifica cantidad de decimal

#--------------------------------------------------------------------------------------------------------------------------
# FILTRAR Y BUSCAR , FILTRO y BUSCAR POR TIPOS DE DATOS
#BUSCAR y manipular nulos y nan
  #da["Nombre Columna"].isnull()--> #--> Nos muestra de forma boolena  las filas vacias de una columna
  #df[df["Nombre de columna"].isnull()] #--> Permite extraer las filas vacias de una columna
  #da.isnull().values.any()--># Nos muestra si tenemos algun nulos o Vacios en el dataframe nan null
  #da.isnull().any() --># Nos muestra con un true que columnas tiene nulos O Vacios nan null
  #da.isnull().sum()--># Nos muestra cuantos nulos o vacios tiene cada columna nan null
  #da.isnull().sum().sum()--># Nos muestra cuantos nulos o vacios tiene el dataframe nan null
  #nan_rows = da[da.isnull().any(1)]--># Nos extrae las columnas que tiene nulos o vacios nan null
  #nan_rows = da[da.isnull().any(1)].head()--># Nos extrae las pirmera 5 columnas con nulos o vacios nan null
  #da.columns[da.isnull().any()]-->#-->#Nos muestra los nombre de las columnas con nulos o vacios nan null
  #df = da.fillna({ 'col 1' : "Sin datos","cl 5" :0, "col 8":"ojo"})--># rellenar valores nulos o vacios nan null
  #da=da.applymap(lambda x:x.lstrip() if isinstance (x, str) else x)--># quitan espacio vacio al inicio en todo el df
  #da=da.applymap(lambda x:x.rstrip() if isinstance (x, str) else x)--># quitan espacio vacio al final en todo el df 
  #da=df.applymap(lambda x:x.strip() if isinstance (x, str) else x)--># quitan espacio vacio al inicio y final en todo el df                                                                       
  #da["nom col1"]=da["nom col1"].str.strip(" ")--># Quitan espacio vacio al inicio y final de toda la columna
  #df = df.fillna(df.mean())-->#Llena un valor vacio con la media de la misma columna 
  #df=da.replace(" ","@",regex=True)--># Remplazar los espacios vacios por @
  #df=da.replace("@"," ",regex=True)--># Remplazar las @ por espacios vacios para reaizar pruebas
  #df=da.dropna(subset=["Nombre columna 1"]) # ---> elimina la fila completa si la columna, si alguna fila de la colum esta vacia,nulo,nan
  #da = da.dropna(how='all') # si toda la fila esta vacia,nulo,nan la elimina
  #df = da.dropna(axis=1, how='all') #---> Elimina columnas totalmente vacias-null-nulo-nulas
  #da = df.select_dtypes(include='object')  #---> Extraer o filtra las columnas de tipo string,object,categorica
  #da = df.select_dtypes(include='float64')  #---> Extraer o filtra las columnas de tipo float o decimal
  #da = df.select_dtypes(exclude='object')  #---> Extraer o filtra las columnas diferentes al tipo string,object,categorica

  #da = list(df.select_dtypes(include='object').columns) #---> extrae solo los nombre de las columnas de tipo string,object,categorica
  #da = list(df.select_dtypes(include='float64').columns) #---> extrae solo los nombre de las columnas de tipo float
  #da = list(df.select_dtypes(exclude='object').columns) #---> extrae solo los nombre de las columnas diferentes al tipo float

#para filtar el mayor apartir de una condicion, condicional, maximo por concional
#da["nombre col 1"]=a["nombre col 1"].replace({"new":"old","new":"old"},regex=True)#-->elimina o remplaza valores de una columna en dataframe
# df=da[(da['nom col1']==2020) & (da["nom col2"]=='amazon')].sort_values(by='duration_int', ascending=False).head(1)
# da.loc[da["nom col 1"] =="valor a buscar", 'nom col 1'] =valor a remplazar ,#--> "cambia" Remplazar un valor por otro en una columna

# da=df[df.nombre columna sin comilla == valor]--># Seleccionamos solo el valor a buscar en la columna que se quiere

   #PANDA.DATAFRAME.FILTER --->OJO, no se puede usar con condicionales
 # FILTER(ITEMS=none, like=none, regex=none, axis=none)
    # filter(items=none)
    # da.filter(items=['columna1','columna2','columna3']) # permite mostrar varios (x) columnas
    # filter(like=none)
    # da.filter(like='ape',axis=1) --> cuando hay muchas columnas y no nos acordamos del nombre -- algo parecido a 'ape' apellidos
    # filter(regex=none,axis=none) por columnas
    #    1.  da.filter(regex='fecha | ano',axis=1) ---> Que alguna columna en su nombre contenga una de las 2 palabras (fecha o ano)
    #    2.  da.filter(regex='\d',axis=1) ---> Que alguna columna en su nombre contenga algun numero
    #    3.  da.filter(regex=ete*',axis=1) ---> Que alguna columna en su nombre contenga estos caracteres (ete)
    #    4.  da.filter(regex='^ed',axis=1) ---> Que alguna columna en su nombre contenga estos caracteres al inicio(ed) ejemplo edad
    #    5.  da.filter(regex='ad$',axis=1) ---> Que alguna columna en su nombre contenga estos caracteres al final(ad) ejemplo edad
    #    6.  da.filter(regex='[g]',axis=1) ---> Que alguna columna en su nombre contenga este caracter en cualquier lugar (g) R//registro,origen
    #    7.  da.filter(regex='xxxxxxx',axis=0) ---> falta ---> un digito seguido de otro digito ejemplo 19 o 54 o 58.

 #BUSCAR  --> (STR.CONTAINS)  -  ( (STR.MATCH) y (STR.STRIP() )  -  (STR.STARTWITH) - (STR.ENDSWITH) )

 # (STR.CONTAINS) # Permite buscar una porcion de una palabra en un string OJO no es exacta
      #STR.CONTAINS('VALOR 1' &(Y/O)  'VALOR 2' &(Y/O) 'VALOR 3', case=False, na=False, regex=True )
                                                            #  case=False: No descrimina mayusculas o minusculas
                                                            #  na=False: Omite vacios
                                                            #  regex=True permite buscar un porcion de texto dentro un string
    # 1. OTRA FORMA 
      #EJEMPLO da['columna'].str.contains('valor1' & / | 'valor2' & / | 'valor3', case=False, na=True, regex=True)
      #        da['NOMBRE'].str.contains('CIHARA' & / | 'CHRIST' & / | 'CARO', case=False, na=True, regex=True)
      #  da[da["nombre col"].str.contains("texto buscar",case=False,na=False,regex=True)]--->
    # 2. OTRA FORMA MAS AUTOMATICA ES CON UNA LISTA 
        # 1.  LISTA_NOMBRES = ['PEDRO','CIHARA','CHRISTIAN','CARO','ANDRES','AURA']
        # 2.  AMIGOS='|'.join(LISTA_NOMBRES)
        # 3.  da[da['NOMBRE'].str.contains(AMIGOS, case=False, na=True, regex=True)]
           
    # 3. OTRA FORMA IGUAL DE AUTOMATICA SIN LISTA 
        # 1.  AMIGOS='|'.JOIN(['PEDRO','CIHARA','CHRISTIAN','CARO','ANDRES','AURA'])
        # 2.  da[da['NOMBRE'].str.contains(LISTA_NOMBRES, case=False, na=True, regex=True)]

 # (STR.STARTWITH) # Permite buscar con las primeras letras de una palabra (Empieza con )
                    # NOTA: 1. No permite usar case=True
                    #       2. si usa LISTAs debe convertira TUPLAS
    # 1. OTRA FORMA
       # 1. da[da['columna donde vamos a buscar'].STR.STARTSWITH('PRIMERAS LETRAS')]
         #  da[da['apellidos'].STR.STARTSWITH('cont')] R// contreras
    
    # 2. OTRA FORMA MAS AUTOMATICA ES CON UNA LISTA --> OJO hay que convertir a tuplas
        # 1. primeras_letras=['cont' , 'la' , 'p']
        # 2. APELLIDOS= '|'.JOIN(primeras_letras)
        # 3. da[da['apellidos'].STR.STARTSWITH(TUPLE(APELLIDOS))] 

 # (STR.ENDSWITH) # Permite buscar con las ultimas letras de una palabra (Termina con )
                    # NOTA: 1. No permite usar case=True
                    #       2. si usa LISTAs debe convertira TUPLAS

    # 1. OTRA FORMA
       # 1. da[da['columna donde vamos a buscar'].STR.ENDSWITH('PRIMERAS LETRAS')]
         #  da[da['apellidos'].STR.ENDSWITH('ras')] R// contreras
    
    # 2. OTRA FORMA MAS AUTOMATICA ES CON UNA LISTA --> OJO hay que convertir a tuplas
        # 1. Ultimas_letras=['ras' , 'ra' , 'o']
        # 2. APELLIDOS= '|'.JOIN(Ultimas_letras)
        # 3. da[da['apellidos'].STR.ENDSWITH(TUPLE(APELLIDOS))] 

 # (STR.MATCH) # Permite buscar una palabra de forma exacta OJO  es exacta 
 # NOTA: para MATCH hay que quitar los espacios en blancos de las palabras con STR.STRIP()

    # 1. OTRA FORMA OJO  es exacta 
        # 1. da['nombre de la columna']=da['nombre de la columna'].STR.STRIP()
        #     EJEMPLO  da['apellidos']=da['apellidos'].str.strip() # limpia las columnas de espacios en blancos
        # 2. da[da['columna'].str.match('valor string x', case=False, na=True, regex=True)]
        #    da[da['apellidos'].str.match('CONTRERAS', case=False, na=True)

    # 2. OTRA FORMA MAS AUTOMATICA ES CON UNA LISTA OJO  es exacta 
         # 1. da['apellidos']=da['apellidos'].str.strip() # limpia las columnas de espacios en blancos
         # 2. LISTA_APELLIDOS=['CONTRERAS','DURAN','LARA']
         # 3. APELLIDOS= '|'.JOIN(LISTA_APELLIDOS)
         # 4. da[da['apellidos'].str.match(APELLIDOS)]
    
    # 3. OTRA FORMA IGUAL DE AUTOMATICA ES SIN LISTAS OJO  es exacta 
         # 1. da['apellidos']=da['apellidos'].str.strip() # limpia las columnas de espacios en blancos
         # 2. APELLIDOS= '|'.JOIN(['CONTRERAS','DURAN','LARA'])
         # 3. da[da['apellidos'].str.match(APELLIDOS)]

  
    
     #BUSCAR Y CONTAR CADA DATO QUE BUSCA              
    #da['columna 1'].str.contains('string a buscar).value_counts()[true] # str.contains y value_counts --> busca y cuenta
   
  #----------------------------------------------------------------------------------------
  #FILTRAR
# variable=da[(da['columna1']=='valor')] # permite filtra depediendo de un valor se manda a otra data llamado d 
# da.groupby('columna a grupar').mean() #filtra y agrupa todos los valores unicos de columna
# APLICAR FUNCIONES A VARIAS COLUMNS CON GROUPBY 
#---------->  da.groupby('columna a grupar').agg({      #filtra y agrupa todos los valores unicos de columna
                                        # aplica funciones de agregacion 
              #OJO CONTINUA -----------># column 1: 'SUM'  , # A esta columna aplica la suma
              #                           column 2: 'MEAN' , # A esta columna aplica la media
              #                           column 3: 'MAX'  , # A esta columna aplica el maximo
              #                                }))
  #--------------------------------------------------------------------------------------------------
            
#da.iloc[0] #Permite octener la primera fila 
#da.iloc[0 : 3] #Permite octener un rango de indices de la primera fila  a la 3-1 fila 
#da[da['columna 1'].str.contains('palabra a buscar o porcion de texto')]# permite ver los datos
#                                                           que contienen esa porcion del texto

# 1 # da['columna 1']>=16 # realiza el filtro que devuelve falsos y verdaderos luego


# 2 # da[ ingresar el filtro ]
# 3 # da[   da['columna 1']>=16     ]   # ingresamos el filtro o condion al dataframe para visualizar los resultados
# evaluar entre mas de una condicion

# 4 # da['columna 2']==18 # realiza el filtro que devuelve falsos y verdaderos luego
  # ingresamos los 2 filtros o condionales al dataframe pero OJO cada filtro dentro de parentisis y ver los resultados 
# 5 # da[    (  da['columna 1']>=16   )  & (  da['columna 2']==1.60   )    ]  
  # ejemplo        edad                  y         altura
 
# Se crean las fechas con la librerÃ­a datetime
# da["fecha"]=pd.to_datetime(df["fecha"],format="%Y%m%d") #--> Cambia el formato de una columna a fecha

            #fecha_1 = Nombre de la instancia del dataframe ejemplo da.datetime(2013, 4, 14)
            #fecha_2 = Nombre de la instancia del dataframe ejemplo da.datetime(2013, 4, 18)
    # Filtro por fecha
           #data_fecha.loc[nombre columna 2 -  fecha_1:nombre columna 2 - fecha_2] 
#no me funcionaron da.duplicated(da.columns[~da.columns.isin(['Entity'])]) #permite hacer la busqueda para borrar parcialmente
#no me funcionaron da.drop_duplicates(da.columns[~da.columns.isin(['Nombre columna'])],keep='first') #--->OJO no se para q es first
#------------------------------------------------------------------------------------------------

#MÃ©todo LOC en DATAFRAME
#BUSCAR o EXTRAER O FILTRAR DE UN DATAFRAME CON -------> LOC Y ILOC
  #SELECIONAR Y BUSCAR POR ETIQUETAS (FILA,NOMBRE COLUMNA)
  #da.loc[indice,'nombre_columna']

  #SELECIONAR Y BUSCAR POR INDICE (INDICE FILA,INDICE COLUMNA)
  #da.iloc[Indice_FILA,Indice_COLUMNA]
  #da.iloc[Indice_FILA]---> Devuelve los valores de la fila con sus titulos

#Se seleccionan los datos del 2 al 4 en el Ã­ndice y las columnas 'rnd_2' y fecha
         #data.loc[2:4, ['rnd_2', 'fecha']]
#--------------------------------------------------------------------------------------------------------
#CONTAR Y ORDENAR
#da['Columna 1'].count() #Permite contar los valor de una columna excluyendo nulo o nan o null o nulo
# #da.count() #cuenta los datos por filas
#da.count(axis=0)#cuenta los datos por filas
#da.count(axis='columns')#cuenta los datos por columnas
#da['Entity'].value_counts()# Permite contar cada uno de los datos de la columna y mostrarlos
#da['Entity'].value_counts(sort=False)# Permite contar cada uno de los datos de la columna y mostrarlos en desorden
#da['Entity'].value_counts(ascending=True)# Permite contar cada uno de los datos de la columna y mostrarlos en orden
#da['Entity'].value_counts(normalize=True)# permite normalizar los datos contados
#da.set_index['Columna a usar como indice'] # permite colocar columnas como indices.
#da['Entity'].value_counts().sort_index(ascending=True)# Ordena por indice al no tener numero en orden alfavetico
#da['Entity'].value_counts().sort_values()# Ordena por valor 
#da['Entity'].value_counts().sort_values().to_frame()# Ordena por valor y mostra en una tabla
#da['Entity'].value_counts().plot(kind="bar") # permite grafricar 
#da['Entity'].value_counts(ascending=True).plot(kind="bar") # permite grafricar de forma ascendente
#da['Entity'].value_counts().to_list()# Permite contar cada uno de los datos y convertir en una lista OJO, 
                                                  #solo muestra los valores.
#da['Entity'].value_counts().keys().to_list() #permite mostrar las claves principales de la columna
#d=da['Entity'].value_counts().to_dict() #permite contar los valor y grupar en un dicionario
#f=da.shape[1] #permite contar el numero de columnas en pandas con el #1 y con el #0 las filas#

#SOLO ORDENAR
#da.sort_values('NOMBRE_COLUMNA1',ascending=True)# Ordena por Columna, asendente de menor a mayor
#da.sort_values('NOMBRE_COLUMNA1',ascending=False)# Ordena por Columna, desendente de mayor a menor 
#da.sort_values(['NOMBRE_COLUMNA1','NOMBRE_COLUMNA2'],ascending=[True,FALSE])# Ordena por 2 Columnas,una asendente la otra no 

#---------------------------------------------------------------------------------------------------
#ELIMINACION
#del(da['Code']) # Elimina una columna por valor
#f=da.drop(columns=['Code','Entity']) # tercera forma de eliminar columnas directamente
#f=da.drop(['columna x '],axis=1) # Cuarta forma de eliminar columnas sin inplace
#f=da.drop(da.columns[[1,3]],axis='columns') # Quinta  forma de eliminar columnas por indice
#f=da.drop('columna x',axis=1, inplace=True) # Sexta forma de eliminar columnas con inplace sin corchetes
           # OJO -->  inplace=True : es para que se aplique el cambio en el dataframe que estamos trabajando
#da = da.drop_duplicates() elimina el duplicado de cada fila
#da.drop_duplicates(['nombre de columna', ''nombre de columna'], keep='last' --->OJO no se para q es last) #Elimina los duplicados de 
#variable = da.dropna() # elimina las filas con los valores con nan o vacios o null o nulo     
#da.drop(da[da[Nom col 1]=="valor"].index, inplace=True) #--> eliminas las filas de la columna nombra que contengan ese valor
    
#da.drop(['Code','Entity'],axis='columns',inplace=True) # primera forma de eliminr columnas
        #keys: Nombre de la columna que se convertirÃ¡ en Ã­ndice. string
        #drop: Elimina la columna que se usarÃ¡ como Ã­ndice. False por defecto.
        #append: Sirve para conservar el Ã­ndice que tiene el dataframe y agregarle uno nuevo. False por defecto.
        #inplace: Modifica el dataframe sobre el que se trabaja, no crea copia. False por defecto.
#------------------------------------------------------------------------------------------------------
#CREAR LLENAR UN DATAFRAME
  #PARA CREAR UN DATAFRAME 
      #    da = pd.DataFrame()---> CREAR UN DATAFRAME, SIN COLUMNAS, NI FILA(INDICES) ---> TOTALMENTE VACIO
      #    da = pd.DataFrame(columns=['NOMBRE1', 'NOMBRE2', 'NOMBRE3'])--> CREA UN DATAFRAME VACIO con columnas
      #    da = pd.DataFrame(columns=['NOMBRE1', 'NOMBRE2', 'NOMBRE3'], index=range(3))--> DATAFRAME VACIO con columnas y indices(filas)
  #PARA LLENAR UN DATAFRAME
      #    da['Nombre'] = None ----> CREA UNA COLUMNA VACIA SOLO CON EL NOMBRE
      #    da['NOMBRE_COLUMNA1'] = ['VALOR1', 'VALOR2',  'VALOR3', 'VALOR4']---> LLENA LAS COLUMNAS DE UN DATA FRAME
      #    da = da.append({'CLAVE': 'VALOR', 'CLAVE':'VALOR', 'CLAVE':'VALOR'}, ignore_index=True)--> Agrega una fila atravez de un dicionario
      #    da.iloc[indice_fila] = ('VALOR_columna1','VALOR_columna2','VALOR_columna3')-->llenar fila por indice
'''   #EJEMPLO
           listaNombres = ['Juan', 'Laura', 'Pepe']
           listaEdades = [42, 40, 37]

           da['Nombre'] = None ----> CREA UNA COLUMNA VACIA SOLO CON EL NOMBRE
           da = da.assign(Edad=None) ----> OTRA FORMA CREA UNA COLUMNA VACIA SOLO CON EL NOMBRE
           
           da['Nombre'] = listaNombres
           da['Edad'] = listaEdades
'''           


#PARA CREAR UNA TUPLA se recomienta q sea atravez de una lista
  # ejemplo #  l=[  (  len(da[da['Entity']=='Colombia']))  ,  (len(da[da['Entity']=='Mexico' ])  )  ]
  #        lista=[  (   cuenta las filas filtradas    ]))  ,  (   cuenta las filas filtradas ])  )  ]
#da['nombre Nueva Columna']=da['columna 1'] +' '+ da['columna 2'] # crear nueva columna

    #------------------------------------------------------------------------------------------------------
    #operaciones entre columnas
    #da['nombre Nueva Columna']=da['columna 1'] /(da['columna 2'] * da['columna 3'])  # crear nueva columna con la operacion entre las otras
            #ejemplo          #da['masa_corporal']=da['peso'] /(da['altura'] * da['altura'])  # crear nueva columna

    #------------------------------------------------------------------------------------------------------
  # MODIFICAR DATOS, LIMPIAR DATOS y CAMBIAR

    # da.loc[da["nombre colum 1"] =="valor a filtrar", 'COLUMNA A MODIFICAR'] =valor a cambiar # --> Permite remplazar, cambiar valores erroneos
    # da["nombre colum 1"]=da["Nombre column 1"].replace(np.nan,0) # --> Permite remplazar, cambiar valores nulos

    # da[["nom col 1",""nom col 2"]].style.hide(axis="index")#-->Oculta los indices de cada fila
    # da[["nom col 1",""nom col 2"]].format(precision=0)#-->Modifica la cantidad de decimal de las columnas
    # da.to_csv("nombre archivo.csv",index=False,sep=";",encoding="utf-8")-->Exporta a csv
    # Apilar varios  DataFrames uno encima del otro con CONCAT, OJO debe tener el mismo numero de columnas
    # DEBAJO_DEL_OTRO = pd.concat([Primer dataframe, Segundo dataframe], axis=0)-->Filas

    # Coloca al lado otro DataFrames (lado a lado)
    # AL_LADO_DEL_OTRO = pd.concat([Primer dataframe, Segundo dataframe], axis=1)-->Columnas
    #----------------------------------------------------------------------------------------------------------------------------
    # Ingresar - insertar, valor,caracter,palabra en una posicion de un campo en un dataframe ejemplo mer8cedes
    #    df['carro'] = df['carro'].apply(lambda x: x[:3] + '8' + x[3:])
    #    da['Nombre col 1'] = df["Nombre col 1"].apply(lambda x: x[:num-indice-posicion] + 'Caracter a ingresar' + x[num-ind-posi:])
    
    # Ingresar - insertar, valor,caracter,palabra al final de un campo en un dataframe ejemplo pedro8 
    #    df['Nombre col 1'] = df['Nombre col 1'].astype(str) + 'Caracter a ingresar' #--> ejemplo el 8
    
    # Ingresar - insertar, valor,caracter,palabra al inicio de un campo en un dataframe ejemplo 8pedro 
    #    df['Nombre col 1'] = "Caracter a ingresar ejemplo el 8" + df['Nombre col 1'].astype(str)
    #----------------------------------------------------------------------------------------------------------------------------
#  
  #Cambia el tipo de dato de las columnas
  #da["nombre de la columna a cambiar"] = da["nombre de la columna a cambiar"].astype(dtype="Int64")
  #da["nombre columna"]=a.round(2) ---> nuemero de decimales que quiero
  # da = da.astype({'nomb col 1': 'float64', 'nomb col 2': 'object'})--> permite cambiar el tipo de datos de varias columnas
  # da['nomb col 1'] = da['nomb col 1'].astype('object') --> permite cambiar el tipo de datos de una columna a string
  # da['nomb col 1'] = da['nomb col 1'].astype('float64')--> permite cambiar el tipo de datos de una columna a float

  #Dividir una columna en 2 usando separadores  y nombrarlas
    # 1.   variable = df["columna a dividir"].str.split(expand=True) #--> cuando posee separadores de como no hay q especificarlos
    # 1.2. variable = df["columna a dividir"].str.split('/',expand=True) #--> cuando posee separadores diferente a comas
    # 2.   variable.columns = ['nombre primera columna dividida', 'nombre segunda columna dividida'] --> nombrar columnas
    
  # RENAME Y INPLACE=TRUE --> Permite renombrar columnas
#EJEMPLO  da.rename(columns={ 'nombre actual de la columna' : 'nuevo nombre' },inplace=True)

  # # ( AT ), ( IAT ) --> Permite ingresar valores a una celda de una dataframe una sola celda

    # ( AT )  = para filas y/o columna que no existen - 
    # ( IAT ) = para filas y/o columna que no existen 

  # ( AT ) 
      # da.at[numero de fila a crear,'nombre columna']=da['nombre columna'].sum() 
# EJEMPLO      daa.at[2,'Year']=daa['Year'].sum()
# LLenar la fila 2 la columna YEAR CON = A LA SUMA DE LA COLUMNA YEAR, OJO SOLO CAMBIO UNA CELDA  

      #da.at[numero de fila a crear,'columna 1']=da['columna 1'].sum() # CREA UNA FILA Y TOTALIZA LA COLUMNA
# EJEMPLO       # daa.at[2,'Year']=daa['Year'].sum() # CREA UNA FILA Y TOTALIZA LA COLUMNA

      #da.at[numero de fila,numero de columna a crear]=da['columna 1'].MAX()
# EJEMPLO       # da.at[ 0 , 8 ]=da['EDAD'].MIN() # CREA UNA COLUMNA Y SACA EL MINIMO A LA FILA
# EJEMPLO       # da.at[ 0 , 8 ]=da['EDAD'].MEAN() # CREA UNA COLUMNA Y SACA LA MEDIA A LA FILA

   # ( IAT )
      #da.iat[ # de fila,# de columna]='Esta vaina esta full buena'
# EJEMPLO       #da.iat[2,4]='Esta vaina esta full buena' # Agrega a la fila 2 columna 3 el testo.


    #---------------------------------------
    #variable = da.fillna( valor a ingresar) # permite rellenar los datos vacios en cada fila donde hay valores -
    #con nan o vacios o null o nulo 

    # permite rellenar los datos vacios de cada fila con diferentes valores
    #variable = da.fillna( { 'COLUMNA 1' : valor a ingresar ,  'COLUMNA 2' : valor a ingresar }) 
    #variable = da.dropna() # elimina las filas con los valores con nan o vacios o null o nulo    
    #--------------------------------------------------------------------------------------------------------
  #APLICAR FUNCIONES EN PANDAS
    #Crear una nueva columna atravez de una funcion, pero esta realiza operaciones complejas (dificiles)
      #SOLO PARA UNA COLUMNA
        #ejemplo:
          # 1      # import random
          # 2      # DEF calcularGanancias(columnas con los datos):
          # 3      # varible ---->  Ganancias = columnas con los datos * random.randint(3,5)
          # 4      #       return Ganancias
          # 5 # da['Ganancias']=da['columnas con los datos'].apply(calcularGanancias)
          #ejemplo: 
          #      da['Nombre nueva columa']=da['columnas con los datos'].apply(Nombre de la funcion)
        #---------------------------------------------------------------------------------------------------------
    #Crear una nueva columna atravez de una funcion, pero esta realiza operaciones complejas (dificiles)
      #SOLO PARA DOS COLUMNA
        #ejemplo:
              
          # 1      # DEF POPULARIDAD(RECIBE TODA LA FILA):
          # 2      # varible ---->  RESULTADO = R TODA LA FILA['NOMBRE COLUMNA 1']/ R TODA LA FILA['NOMBRE COLUMNA 2']
          # 3      #       return RESULTADO

      # 4 # da['POPULARIDAD']=da.APPLY(POPULARIDAD,AXIS=1)
      #ejemplo: 
      #      da['Nombre nueva columa']=da.APPLY(POPULARIDAD,AXIS=1)
                     #OJO NOTA AXIS=1 LE ESPACIFICA APPLY() QUE SE REALICE POR CADA FILA

# ESTADISTICAS
  #Hallar el promedio o media Arimetica en Numpy con np.mean(variable con la muestra)
      # ejemplo 
      # Muestra = np.array( [[1.85, 1.8, 1.8 , 1.8],  [1.73,  1.7, 1.75, 1.76])
      # variable=np.mean(Muestra) ---> Esta seria la media o promedio
  #Hallar el PROMEDIO O MEDIA, MODA, MEDIANA,VARIANZA, FRECUENCIA,INFORMACION,DESCRIPCION 
  #PARA DATAFRAME:
        #da.info()--> muestra la info del dataframe  
        #da.describe()-->muestra todos los datos estadisticos de las comunas numericas
        #da.describe(include="all")-->muestra todos los datos estadisticos de todas las columnas
        # da.boxplot()-->
        #da.mean()-->media
        #da.mode()-->moda
        #da.median()-->mediana
        #da.var()-->varianza
  
  #PARA UNA COLUMNA DEL DATAFRAME:
  # da['NOMBRE_COLUMNA'] 
#--------------------------------------------------------------------------------
    #FACTORIZAR para estadisticas y probabilidades
    #Funcion para hallar factorial
    #PRIMERA FORMA
        # def factorial(num):
        #    fac=num
        #    l=range(1,fac+1)
        #    l=list(l)
        #    for i in l[:-1]:
        #      fac=fac*i
        #    return fac 
    #SEGUNAD FORMA
    # from math import factorial
        #CombinaciÃ³n ----> NO IMPORTA EL ORDEN LA MUESTRA----da el mismo resultado sin importar el ORDEN
              #  control_aeropuerto = factorial(10) / (factorial(3) * factorial(10-3))
              #  print(control_aeropuerto)

        #PermutaciÃ³n ----> ES IMPORTANTE EL ORDEN LA MUESTRA---por que puede dar diferentes resultados
              #  control_aeropuerto = factorial(10) / factorial(10-3)
              #  print(control_aeropuerto)   
          
#Conocer los valores unicos de cada columnas y pasar a un dataframe los Subniveles
# para saber si tienen valores unicos 
# 
# #  } = alt 125
#  { = alt 123
#--------------------------
#    listNivel=[]
#    nomCol=[]

#    for col in ColumCatego:
#        listNivel.append(col)
#        nomCol.append(dataHospital[col].nunique())
#        #print(f"columna { col } : { dataHospital[col].nunique()}  subniveles")
#    subniveles=pd.DataFrame(list(zip(nomCol,listNivel)),columns=["Nombre","Subniveles"])
#    subniveles  
#--------------------------------------------------------------------------------------------------------
# Cambiar todos los string cambiar minuscula a mayusc del dataframe  a minusculas con un bucle 
#   
# col_categoricas = df.select_dtypes(include='object') 
# for col in dataGeneral:
#    if col in col_categoricas:
#       dataGeneral[col]=dataGeneral[col].str.lower()
#-------------------------------------------------------------------------------------------------------
# df.rename(columns=lambda x: x.lower(),inplace=True) #--> cambiar los nombres de las columnas a minusculas
# df.rename(columns=lambda x: x.upper(),inplace=True) #--> cambiar los nombres de las columnas a mayusculas
#--------------------------------------------------------------------------------------------------------
# 1 Extrar er datos de una web en formato http y pasar a pandas
#--------------------------------------------------------------------------------------------------------
        # import pandas as pd
        # import requests
        # import io

        # url = 'https://datacatalogfiles.worldbank.org/ddh-published/0038044/DR0046259/skill_migration_public.csv'
        # response = requests.get(url)

        # data = response.text.splitlines()
        # csv_file = io.StringIO('\n'.join(data))

        # df = pd.read_csv(csv_file)
        # df.head(1)

#--------------------------------------------------------------------------------------------------------
# 2 Extrar er datos de una web en formato http y pasar a pandas
#--------------------------------------------------------------------------------------------------------
      # import io
      # import pandas as pd
      # import requests

      # url = 'https://datacatalogfiles.worldbank.org/ddh-published/0038044/DR0046259/skill_migration_public.csv'
      # response = requests.get(url)
      # data = response.content.decode('utf-8')

      # df = pd.read_csv(io.StringIO(data))
      # df.head(1)
#---------------------------------------------------------------------------------------------------------------------------------------
#------------------------------------------------------------------------------------------------------------------------------------------------
#  AMBIENTES VIRTUALES, ARRANCADORES FLASK, FASTAPI

   #link
#para EJECUTAR la api
# https://fastapi-platafomas-streaming.onrender.com/docs
    
#python -m venv venv #--> crear el ambiente virtual desde la terminal
#crear el main.py #--> crear un archivo en el ambinete virtual
#cd
#.\venv\
#Set-ExecutionPolicy -ExecutionPolicy Remotesigned -Scope process
#.\Scripts\
#.\activate
#cd ..
#cd ..
#uvicorn main:app
#uvicorn main:app --reload  #---> para que quede cocorriendo mientras dse programa
#http://localhost:8000
#http://localhost:8000/docs 
#Para hacer del deploy --> renderizar 
#pip list
#pip uninstall pandas,numpy,etc
#uvicorn main:app --host 0.0.0.0 --port 8080  
#environment environment variables--> key:PIP_VERSION   value:22.3.1 #-->version
#pip install --upgrade scikit-learn
#pip freeze > requirements.txt

#-----------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------

"   #EJEMPLO\n           listaNombres = ['Juan', 'Laura', 'Pepe']\n           listaEdades = [42, 40, 37]\n\n           da['Nombre'] = None ----> CREA UNA COLUMNA VACIA SOLO CON EL NOMBRE\n           da = da.assign(Edad=None) ----> OTRA FORMA CREA UNA COLUMNA VACIA SOLO CON EL NOMBRE\n           \n           da['Nombre'] = listaNombres\n           da['Edad'] = listaEdades\n"